# -*- coding: utf-8 -*-
"""forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRo0zf6ejwjB0tZpN47otHgiYGB-fRVS
"""

import streamlit as st
import pandas as pd
import numpy as np
import os
import glob
import plotly.express as px

# Set title
st.title("📊 Childcare Staffing Forecast Dashboard")

# Load forecast files
forecast_files = glob.glob('forecast_next_week_*.csv')

if not forecast_files:
    st.warning("No forecast files found in this directory.")
    st.stop()

# Combine forecasts
all_data = []
for file in forecast_files:
    room = os.path.basename(file).replace('forecast_next_week_', '').replace('.csv', '').replace('_', ' ')
    df = pd.read_csv(file, parse_dates=['ds'])
    df['Room'] = room
    all_data.append(df)

df = pd.concat(all_data).sort_values('ds')

# Sidebar filters
rooms = sorted(df['Room'].unique())
selected_room = st.sidebar.selectbox("Select Room", options=['All Rooms'] + rooms)

# Filter data
if selected_room != 'All Rooms':
    filtered_df = df[df['Room'] == selected_room]
else:
    filtered_df = df.copy()

# Line chart: Student count forecast
st.subheader(f"📈 Forecasted Student Count ({selected_room})")
fig_students = px.line(
    filtered_df,
    x='ds',
    y='yhat',
    color='Room' if selected_room == 'All Rooms' else None,
    labels={'ds': 'Date & Time', 'yhat': 'Student Count'},
    title='Student Forecast (30-min intervals)'
)
st.plotly_chart(fig_students, use_container_width=True)

# Line chart: Staff needed
st.subheader("🧑‍🏫 Estimated Staff Required")
if 'EstimatedStaff' in filtered_df.columns:
    if selected_room == 'All Rooms':
        total_staff = filtered_df.groupby('ds')['EstimatedStaff'].sum().reset_index()
        fig_staff = px.line(
            total_staff,
            x='ds',
            y='EstimatedStaff',
            labels={'ds': 'Date & Time', 'EstimatedStaff': 'Total Staff'},
            title='Total Staff Required Across All Rooms'
        )
    else:
        fig_staff = px.line(
            filtered_df,
            x='ds',
            y='EstimatedStaff',
            labels={'ds': 'Date & Time', 'EstimatedStaff': 'Staff Count'},
            title=f"Staff Needed for {selected_room}"
        )
    st.plotly_chart(fig_staff, use_container_width=True)
else:
    st.info("No EstimatedStaff column found in the uploaded forecast files.")

# Daily max staff summary
st.subheader("📆 Daily Maximum Staff Requirement")
df['Date'] = df['ds'].dt.date
daily_summary = df.groupby(['Room', 'Date'])['EstimatedStaff'].max().reset_index()
if selected_room != 'All Rooms':
    daily_summary = daily_summary[daily_summary['Room'] == selected_room]
st.dataframe(daily_summary.rename(columns={'EstimatedStaff': 'Max Staff Needed'}))

# Heatmap: Staff Need by Hour and Day
st.subheader("🌡️ Heatmap of Staff Demand by Hour and Day")
df['Hour'] = df['ds'].dt.hour
df['Day'] = df['ds'].dt.day_name()
heatmap_data = df.groupby(['Day', 'Hour'])['EstimatedStaff'].sum().unstack()
fig_heatmap = px.imshow(
    heatmap_data,
    labels=dict(x="Hour", y="Day", color="Staff Needed"),
    title="Staff Demand Heatmap by Hour and Day"
)
st.plotly_chart(fig_heatmap, use_container_width=True)

# Download forecast data
st.subheader("⬇️ Download Forecast Data")
csv = filtered_df.to_csv(index=False).encode()
st.download_button(
    label="Download Filtered Forecast as CSV",
    data=csv,
    file_name=f"{selected_room.replace(' ', '_')}_forecast.csv",
    mime='text/csv'
)

# Notes about assumptions
st.markdown("""
---
**📌 Notes:**
- Forecasts are based on Prophet models trained on historical check-in data.
- Student counts are rounded to whole numbers.
- Staff estimates are based on room-specific ratios using `ceil(student_count / ratio)`.
- Heatmap helps visualize staffing trends across weekdays and hours.
""")